document.write("<section class=\"nav-section\">");
document.write("");
document.write("        <!-- Logo -->");
document.write("        <div class=\"logo\">");
document.write("          <a href=\"index.html\" title=\"Frivizn logo\">The Canadian Populist<\/a>");
document.write("        <\/div>");
document.write("");
document.write("        <!-- Navigation -->");
document.write("        <nav class=\"nav-menu\" role=\"navigation\">");
document.write("          <ul class=\"nav-links\">");
document.write("            <li><a href=\"index.html\" title=\"Home\">Home<\/a><\/li>");
document.write("            <li><a href=\"article.html\" title=\"World\">World<\/a>");
document.write("            <li><a href=\"politics.html\" title=\"Politics\">Politics<\/a><\/li>");
document.write("            <li><a href=\"business.html\" title=\"Business\">Business<\/a><\/li>");
document.write("            <li><a href=\"sport.html\" title=\"Sport\">Sport<\/a><\/li>");
document.write("            <li><a href=\"entertainment.html\" title=\"Entertainment\">Entertainment<\/a><\/li>");
document.write("            <li>");
document.write("              <a href=\"#more\" title=\"More\">More...<span class=\"dropdown-toggle\" aria-expanded=\"false\"><\/span>");
document.write("                <span class=\"screen-reader-text\">Expand child menu<\/span><\/a>");
document.write("              <ul class=\"sub-menu\">");
document.write("                <li><a href=\"#\" title=\"Science\">Science<\/a><\/li>");
document.write("                <li><a href=\"#\" title=\"Travel\">Travel<\/a><\/li>");
document.write("                <li><a href=\"#\" title=\"Health\">Health<\/a><\/li>");
document.write("                <li><a href=\"#\" title=\"Style\">Style<\/a><\/li>");
document.write("                <li><a href=\"#\" title=\"Weather\">Weather<\/a><\/li>");
document.write("                <li><a href=\"#\" title=\"Video\">Video<\/a><\/li>");
document.write("              <\/ul>");
document.write("            <\/li>");
document.write("          <\/ul>");
document.write("          <div class=\"burger\">");
document.write("            <div class=\"line-1\"><\/div>");
document.write("            <div class=\"line-2\"><\/div>");
document.write("            <div class=\"line-3\"><\/div>");
document.write("          <\/div>");
document.write("        <\/nav>");
document.write("      <\/section> <!-- end of class=\"nav-section\"-->");
document.write("");
